---
minVersion: "0.15.0"
github:
  owner: getsentry
  repo: sentry-netlify-build-plugin
changelogPolicy: none
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: npm
    access: public
  - name: github
    tagPrefix: v
